version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "INTERNAL"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "INTERNAL"
